AutoBooking2/Controllers/HomeController.cs
using System;
using System.Data.Entity;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoBooking2.Helper;
using AutoBooking2.Models;
using Newtonsoft.Json;
using BookingDomainService;

namespace AutoBooking2.Controllers
{
    public class HomeController : Controller
    {
        private SystemLogDBContext db = new SystemLogDBContext();

        public async Task<ActionResult> Index()
        {
            return View(await db.BookingModel.FirstOrDefaultAsync());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Save(string traner, string owner, DateTime classDate, bool enable, string cookies)
        {
            try
            {
                var bookingModel = new BookingInfo { ID = 1, Traner = traner, Owner = owner, ClassDate = classDate, Cookies = cookies };
                db.Entry(bookingModel).State = EntityState.Modified;
                db.SaveChangesAsync();
                LogHelper.WriteLog("Save", JsonConvert.SerializeObject(bookingModel), LogType.Info);

                BookingService.GetInstance().SetBookingDate(); 
            }
            catch (Exception ex)
            {
                LogHelper.WriteLog("Booking Error", ex.Message, LogType.Error);
                return Json(new { Message = ex.Message });
            }
            return Json(new { Message = "保存成功" });
        }

        public async Task<ActionResult> Booking(string traner, string owner, DateTime classTime, string cookies)
        {
            try
            {
                var bookingModel = new BookingInfo { ID = 1, Traner = traner, Owner = owner, ClassDate = classTime, Cookies = cookies };
                db.Entry(bookingModel).State = EntityState.Modified;
                db.SaveChangesAsync();

                BookingService.GetInstance().Book();
            }
            catch (Exception ex)
            {
                LogHelper.WriteLog("Booking Error", ex.Message, LogType.Error);
                return Json(new { Message = ex.Message });
            }
            return Json(new { Message = "预定成功" });
        }
    }
}

AutoBooking2/Controllers/SystemLogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoBooking2.Models;

namespace AutoBooking2.Controllers
{
    public class SystemLogsController : Controller
    {
        private SystemLogDBContext db = new SystemLogDBContext();

        // GET: SystemLogs
        public async Task<ActionResult> Index(string title,DateTime? timeFrom,DateTime? timeTo,string Types)
        {
            var logs = db.Log.Select(p => p);
            if (timeFrom.HasValue && timeTo.HasValue)
            { logs = logs.Where(p => p.DataChange_lasttime >= timeFrom && p.DataChange_lasttime <= timeTo); }
            
            if (!string.IsNullOrEmpty(title))
            {
                logs = db.Log.Where(p => p.Title == title);
            }
            if (!string.IsNullOrEmpty(Types))
            {
                logs = db.Log.Where(p => p.Type == Types);
            }
            ViewBag.Types = new SelectList(db.Log.Select(p => p.Type).Distinct());

            return View(await logs.OrderByDescending(p=>p.DataChange_lasttime).ToListAsync());
        }

        // GET: SystemLogs/Details/5
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SystemLog systemLog = await db.Log.FindAsync(id);
            if (systemLog == null)
            {
                return HttpNotFound();
            }
            return View(systemLog);
        }

        // GET: SystemLogs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SystemLogs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Title,Message,StackTrace,DataChange_lasttime")] SystemLog systemLog)
        {
            if (ModelState.IsValid)
            {
                db.Log.Add(systemLog);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(systemLog);
        }

        // GET: SystemLogs/Edit/5
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SystemLog systemLog = await db.Log.FindAsync(id);
            if (systemLog == null)
            {
                return HttpNotFound();
            }
            return View(systemLog);
        }

        // POST: SystemLogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Title,Message,StackTrace,DataChange_lasttime")] SystemLog systemLog)
        {
            if (ModelState.IsValid)
            {
                db.Entry(systemLog).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(systemLog);
        }

        // GET: SystemLogs/Delete/5
        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SystemLog systemLog = await db.Log.FindAsync(id);
            if (systemLog == null)
            {
                return HttpNotFound();
            }
            return View(systemLog);
        }

        // POST: SystemLogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            SystemLog systemLog = await db.Log.FindAsync(id);
            db.Log.Remove(systemLog);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutoBooking2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AutoBooking2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AutoBooking2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@model AutoBooking2.Models.BookingInfo
<script type="text/javascript">
    $(function () {
        $('#ClassTime').datetimepicker({
            defaultDate: '@DateTime.Now.AddDays(1).Date',
            format: "YYYY/MM/DD HH:mm"
        });
        $(".dropdown-menu li a").click(function () {
            $("#Trainer").html($(this).text() + '<span class="caret pull-right"></span>');
            $("#Trainer").val($(this).attr("value"));
        });
    });

    function Booking() {
        var traner = $("#Trainer").text();
        var owner = $("input[name='Owner']:checked").val();
        var classTime = $("#ClassTime input").val();
        var enable = $("#Enable").is(":checked");
        var cookies = $("#Cookies textarea").val();

        $.ajax({
            url: "@(Url.Action("Booking"))",
            type: "POST",
            data: { traner: traner, owner: owner, classTime: classTime, enable: enable, cookies: cookies },
            success: function (rsp) {
                alert(rsp.Message);
            }
        })
    }

    function Save() {
        var traner = $("#Trainer").text();
        var owner = $("input[name='Owner']:checked").val();
        var classTime = $("#ClassTime input").val();
        var enable = $("#Enable").is(":checked");
        var cookies = $("#Cookies textarea").val();

        $.ajax({
            url: "@(Url.Action("Save"))",
            type: "POST",
            data: { traner: traner, owner: owner, classDate: classTime, enable: enable, cookies: cookies },
            success: function (rsp) {
                alert(rsp.Message);
            }
    })
    }
</script>

<style>
    body {
        font-family: 'Microsoft YaHei';
    }

    label {
        font-size: 18px;
    }

    input {
        max-width: 600px;
    }
</style>

<div class="jumbotron">
    <h1>邬少的自动约课机器人<small> Beta 1.0</small></h1>
</div>

<div class="row">
    <div>
        <div class='col-md-6'>
            <div class="form-group">
                <label class="control-label">私教</label>
                <div class="dropdown">
                    <button style="width:300px" class="btn btn-default dropdown-toggle" type="button" id="Trainer" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        请选择私教
                        <span class="caret pull-right"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="Trainer">
                        <li><a href="#" value="1022198">Alan</a></li>
                        <li><a href="#" value="1022193">Vito</a></li>
                    </ul>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label">受虐者</label>
                <div>
                    <div class="radio radio-inline">
                        <label>
                            <input type="radio" name="Owner" value="W" checked>
                            世界上最帅的人
                        </label>
                        &nbsp;&nbsp;
                        <label>
                            <input type="radio" name="Owner" value="C">
                            世界上最美的人
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label">上课时间</label>
                <div class='input-group date' id='ClassTime'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" id="Enable">
                        自动约课
                    </label>
                </div>
            </div>
        </div>
        <div class='col-md-6'>
            <div class="form-group">
                <label class="control-label">Cookies</label>
                <div class='input-group date' id='Cookies'>
                    <textarea style="max-width: 555px; width: 555px" type='text' class="form-control" rows="13">
                        @Model.Cookies
                    </textarea>
                </div>
            </div>
        </div>
    </div>
    <div class="text-center">
        <button class="btn btn-lg btn-primary" id="Save" onclick="Save()"><i class="glyphicon glyphicon-floppy-disk"></i> 保存</button>
        <button class="btn btn-lg btn-primary" id="BookingNow" onclick="Booking()"><i class="glyphicon glyphicon-ok"></i> 现在约课</button>
    </div>
    <div class="text-right">
        @Html.ActionLink("查看日志","Index", "SystemLogs",null, new { target = "_blank" })
    </div>
</div>